kind: Secret
apiVersion: v1
metadata:
  name: demo-secret
data:
  MYSQL_HOST: <base 64 encoded host>
  MYSQL_PASSWORD: <base 64 encoded password>
  MYSQL_USER: <base 64 encoded user>
  MYSQL_DATABASE: <base 64 encoded database>
type: Opaque